import { ImageResponse } from 'next/og';
import { NextRequest } from 'next/server';

export const runtime = 'edge';

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const title = searchParams.get('title') || 'AI Workflow Blueprint';
    const type = searchParams.get('type') || 'Custom Automation';
    const impact = searchParams.get('impact') || 'Optimized';

    return new ImageResponse(
      (
        <div
          style={{
            height: '100%',
            width: '100%',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: '#0a0a0a',
            backgroundImage: 'radial-gradient(circle at 50% 50%, #1a1a1a 0%, #0a0a0a 100%)',
            padding: '40px 80px',
            color: 'white',
            fontFamily: 'Inter, sans-serif',
          }}
        >
          {/* Logo/Brand */}
          <div style={{ position: 'absolute', top: 60, left: 80, display: 'flex', alignItems: 'center', gap: 12 }}>
            <div style={{ width: 40, height: 40, borderRadius: 12, background: 'linear-gradient(135deg, #60a5fa 0%, #a78bfa 100%)' }} />
            <span style={{ fontSize: 32, fontWeight: 900, letterSpacing: '-0.05em' }}>Thinkly</span>
          </div>

          {/* Main Content */}
          <div style={{ display: 'flex', flexDirection: 'column', marginTop: 40 }}>
            <div style={{ fontSize: 20, fontWeight: 800, color: '#a78bfa', textTransform: 'uppercase', letterSpacing: '0.2em', marginBottom: 12 }}>
              {type}
            </div>
            <div style={{ fontSize: 64, fontWeight: 900, lineHeight: 1.1, marginBottom: 24, maxWidth: '800px' }}>
              {title}
            </div>
            
            <div style={{ display: 'flex', gap: 24 }}>
              <div style={{ display: 'flex', flexDirection: 'column', background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.1)', padding: '16px 24px', borderRadius: 20 }}>
                <span style={{ fontSize: 16, color: 'rgba(255,255,255,0.4)', fontWeight: 600, textTransform: 'uppercase' }}>Workflow Impact</span>
                <span style={{ fontSize: 32, fontWeight: 800, color: '#60a5fa' }}>{impact}</span>
              </div>
            </div>
          </div>

          {/* Subtle decoration */}
          <div style={{ position: 'absolute', bottom: 60, right: 80, fontSize: 18, color: 'rgba(255,255,255,0.2)', fontWeight: 500 }}>
            thinkly.app • Generated by AI
          </div>
        </div>
      ),
      {
        width: 1200,
        height: 630,
      }
    );
  } catch (e: any) {
    return new Response(`Failed to generate image`, { status: 500 });
  }
}
